/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    Server: {
      service: string
      type: 'sst.aws.Service'
      url: string
    }
    Vpc: {
      bastion: string
      type: 'sst.aws.Vpc'
    }
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst'
